title: Beemen Sameh Resume # your name (or website title) here
logo: "https://avatars.githubusercontent.com/u/41084077" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A passionate Back-End developer with a demonstrated history of work in computer software. Work with Python, PHP, Database Development (SQL Server, MySQL, Postgres). And I developed many Laravel, Django, Golang projects.

profile:
  github: https://github.com/beemensameh
  linkedin: https://www.linkedin.com/in/beemensameh/

theme: jekyll-theme-minimal
